// Generated by CoffeeScript 1.9.1
(function() {
  'use strict';
  var _, categories_db, io;

  categories_db = require('../../models/categories_db');

  io = require('../io');

  _ = require('lodash');

  module.exports = function(req, res, next) {
    var category;
    category = req.body;
    categories_db.categories.view('byTitle/byTitle', {
      key: req.body.title,
      include_docs: true
    }, function(err, docs) {
      if (docs.length > 0) {
        return io.show('категория' + req.body.title + 'уже существует', 'error');
      } else {
        return categories_db.categories.save(category, function(err, res) {
          if (err) {
            io.show('ошибка при создании категории' + req.body.title, 'error', err);
          } else {
            io.show('категория ' + req.body.title + ' успешно создана', 'success');
          }
        });
      }
    });
    next();
  };

}).call(this);
