// Generated by CoffeeScript 1.9.1
(function() {
  'use strict';
  var passport;

  passport = require('passport');

  module.exports = function(req, res, next) {
    console.log('someone trying to login');
    passport.authenticate('local', function(err, user, info) {
      console.log('err:', err);
      console.log('user:', user);
      if (err) {
        return res.redirect('/user/fail');
      }
      if (!user) {
        req.session.messages = info.message;
        return res.redirect('/user/fail');
      }
      return req.logIn(user, (function(err) {
        if (err) {
          req.session.messages = "Error";
          return next(err);
        }
        req.session.messages = "Login successfully";
        return res.redirect('/');
      }));
    })(req, res, next);
  };

}).call(this);
