// Generated by CoffeeScript 1.9.1
(function() {
  'use strict';

  /**
   * Module dependencies.
   */
  module.exports = function(req, res) {
    req.logout();
    res.redirect('/');
  };

}).call(this);
