// Generated by CoffeeScript 1.9.1
(function() {
  'use strict';

  /**
   * Module dependencies.
   */
  var couch;

  couch = require('../../models/couch');

  module.exports = function(req, res, next) {
    console.log(req.body.email);
    couch.users.get(req.body.email, function(err, doc) {
      if (err && err.error === 'not_found') {
        return couch.users.save(req.body.email, {
          email: req.body.email,
          password: req.body.password
        }, function(err, res) {});
      }
    });
    next();
  };

}).call(this);
