// Generated by CoffeeScript 1.9.1
(function() {
  var _, bills, express, router, spawn;

  express = require('express');

  router = express.Router();

  bills = require('../controllers/bills');

  spawn = require('child_process');

  _ = require('lodash');

  router.get('/restart', function(req, res, next) {
    console.log('restart');
    spawn.exec('sudo /usr/sbin/service homebook restart', function(error, stdout, stderr) {
      console.log('stdout: ' + stdout);
      console.log('stderr: ' + stderr);
      if (error !== null) {
        console.log('exec error: ' + error);
      }
    });
  });

  module.exports = router;

}).call(this);
