// Generated by CoffeeScript 1.9.1
(function() {
  var adminHandler, express, requireAuth, router, users;

  express = require('express');

  router = express.Router();

  users = require('../controllers/users');


  /* GET users listing. */

  requireAuth = function(req, res, next) {
    console.log(req.isAuthenticated());
    if (!req.isAuthenticated()) {
      req.session.messages = 'You need to login to view this page';
      res.redirect('/user/login');
    } else {
      next();
    }
  };

  adminHandler = function(req, res, next) {
    console.log('ADMIN!!!!!');
    console.log(req.user);
  };

  router.post('/login', users.login, function(req, res, next) {
    res.render('index', {
      title: 'Express'
    });
  });

  router.get('/login', function(req, res, next) {
    res.render('user/login', {
      title: 'Express'
    });
  });

  router.get('/register', function(req, res, next) {
    res.render('user/register', {
      title: 'Express'
    });
  });

  router.post('/register', users.register, function(req, res, next) {
    res.render('index', {
      title: 'Express'
    });
  });

  router.get('/logout', users.logout);

  router.get('/fail', function(req, res, next) {
    res.render('user/fail', {
      title: 'Express'
    });
  });

  router.get('/admin', requireAuth, adminHandler);

  module.exports = router;

}).call(this);
