// Generated by CoffeeScript 1.9.1
(function() {
  var bills, express, router;

  express = require('express');

  router = express.Router();

  bills = require('../controllers/bills');

  router.get('/create', function(req, res, next) {
    res.render('bill/create');
  });

  router.get('/all', bills.all, function(req, res, next) {
    console.log('get all');
    res.render('bill/all');
  });

  router.post('/create', bills.create, function(req, res, next) {
    res.send(res.body);
  });

  module.exports = router;

}).call(this);
