// Generated by CoffeeScript 1.9.1
(function() {
  var category, express, router;

  express = require('express');

  router = express.Router();

  category = require('../controllers/categories');

  router.get('/create', function(req, res, next) {
    console.log('restart');
    res.render('category/create');
  });

  router.post('/create', category.create, function(req, res, next) {
    res.send({
      success: true
    });
  });

  module.exports = router;

}).call(this);
