// Generated by CoffeeScript 1.9.1
(function() {
  var express, products, router;

  express = require('express');

  router = express.Router();

  products = require('../controllers/products');

  router.get('/create', function(req, res, next) {
    res.render('product/create');
  });

  router.post('/create', products.create, function(req, res, next) {
    res.render('product/create');
  });

  module.exports = router;

}).call(this);
