// Generated by CoffeeScript 1.9.1
(function() {
  var express, router, shops;

  express = require('express');

  router = express.Router();

  shops = require('../controllers/shops');

  module.exports = router;

}).call(this);
