// Generated by CoffeeScript 1.9.1
(function() {
  var adminHandler, express, requireAuth, router, users, winston;

  express = require('express');

  router = express.Router();

  users = require('../controllers/users');

  winston = require('winston');

  requireAuth = function(req, res, next) {
    if (!req.isAuthenticated()) {
      req.session.messages = 'You need to login to view this page';
      res.redirect('/user/login');
    } else {
      next();
    }
  };

  adminHandler = function(req, res, next) {};

  router.post('/login', users.login, function(req, res, next) {
    res.redirect('/', {
      title: 'Express'
    });
  });

  router.get('/login', function(req, res, next) {
    winston.log('info', 'Test Log Message', {
      anything: 'This is metadata'
    });
    res.render('user/login', {
      title: 'Express'
    });
  });

  router.get('/register', function(req, res, next) {
    res.render('user/register', {
      title: 'Express'
    });
  });

  router.post('/register', users.register, function(req, res, next) {
    res.redirect('/', {
      title: 'Express'
    });
  });

  router.get('/logout', users.logout);

  router.get('/fail', function(req, res, next) {
    res.render('user/fail', {
      title: 'Express'
    });
  });

  router.get('/admin', requireAuth, adminHandler);

  module.exports = router;

}).call(this);
