// Generated by CoffeeScript 1.9.1
(function() {
  'use strict';
  var couch;

  couch = require('../../models/couch');

  module.exports = function(req, res, next) {
    couch.clearBase();
    next();
  };

}).call(this);
