// Generated by CoffeeScript 1.9.1
(function() {
  'use strict';
  var _, spawn;

  spawn = require('child_process');

  _ = require('lodash');

  module.exports = function(req, res, next) {
    if (req.user) {
      spawn.exec('sudo /usr/sbin/service homebook restart', function(error, stdout, stderr) {
        console.log('stdout: ' + stdout);
        console.log('stderr: ' + stderr);
        if (error !== null) {
          console.log('exec error: ' + error);
        }
      });
    }
    next();
  };

}).call(this);
