// Generated by CoffeeScript 1.9.1
(function() {
  module.exports.restart = require('./admin/restart');

  module.exports.replicateTo = require('./admin/replicateTo');

  module.exports.replicateFrom = require('./admin/replicateFrom');

  module.exports.clearBase = require('./admin/clearBase');

}).call(this);
