// Generated by CoffeeScript 1.9.1
(function() {
  var app, io;

  app = require('../app');

  io = require('socket.io')();

  module.exports.init = function(server) {
    console.log('init io');
    io.attach(server);
    io.on('connection', function(socket) {
      console.log('io connection');
    });
  };

  module.exports.show = function(text, type, data) {
    data = data || null;
    type = !type ? 'success' : type;
    io.sockets.emit(type, {
      message: text,
      data: data
    });
    setTimeout(function() {
      text = '(дубль) ' + text;
      return io.sockets.emit(type, {
        message: text,
        data: data
      });
    }, 3000);
  };

}).call(this);
