// Generated by CoffeeScript 1.9.1
(function() {
  module.exports.products = require('./lists/products');

  module.exports.shops = require('./lists/shops');

  module.exports.categories = require('./lists/categories');

}).call(this);
