// Generated by CoffeeScript 1.9.1
(function() {
  module.exports.login = require('./users/login');

  module.exports.logout = require('./users/logout');

  module.exports.register = require('./users/register');

}).call(this);
