// Generated by CoffeeScript 1.9.1
(function() {
  'use strict';
  var io, products_db;

  products_db = require('../../models/products_db');

  io = require('../io');

  module.exports = function(req, response, next) {
    var product;
    product = req.body;
    if (req.body.title) {
      if (req.body.category && !req.body.category_id) {
        response.body = {
          success: false,
          err: 'category_id not provided'
        };
        next();
      } else {
        products_db.products.save(product, function(err, res) {
          io.show('продукт' + req.body.title + 'успешно создан', 'success');
          response.body = {
            success: true,
            id: res.id
          };
          next();
        });
      }
    } else {
      response.body = {
        success: false,
        err: 'title not provided'
      };
      next();
    }
  };

}).call(this);
