// Generated by CoffeeScript 1.9.1
(function() {
  'use strict';
  var _, io, purchases_db;

  _ = require('lodash');

  purchases_db = require('../../models/purchases_db');

  io = require('../io');

  module.exports = function(req, response, next) {
    var purchase_items;
    purchase_items = [];
    purchases_db.view('all/all', {
      include_docs: true
    }, function(err, res) {
      console.log(res);
      _.each(res, function(row) {
        return purchase_items.push({
          id: row.id,
          doc: row.doc
        });
      });
      response.locals.purchases = purchase_items;
      next();
    });
  };

}).call(this);
