// Generated by CoffeeScript 1.9.1
(function() {
  'use strict';
  var _, bills_db, io;

  _ = require('lodash');

  bills_db = require('../../models/bills_db');

  io = require('../io');

  module.exports = function(req, response, next) {
    var bill_items;
    bill_items = [];
    bills_db.view('all/all', {
      include_docs: true
    }, function(err, res) {
      console.log(res);
      _.each(res, function(row) {
        return bill_items.push({
          id: row.id,
          doc: row.doc
        });
      });
      console.log(bill_items);
      response.locals.bills = bill_items;
      next();
    });
  };

}).call(this);
