// Generated by CoffeeScript 1.9.1
(function() {
  'use strict';

  /**
   * Module dependencies.
   */
  var bills_db;

  bills_db = require('../../models/bills_db');

  module.exports = function(req, res, next) {
    console.log(req.body);
    next();
  };

}).call(this);
