// Generated by CoffeeScript 1.9.1
(function() {
  'use strict';
  var io, shops_db;

  shops_db = require('../../models/shops_db');

  io = require('../io');

  module.exports = function(req, response, next) {
    var shop;
    shop = req.body;
    shops_db.save(shop, function(err, res) {
      if (err) {
        return;
      }
      io.show('магазин' + req.body.title + 'успешно создан', 'success');
      response.body = {
        success: true,
        id: res.id
      };
      next();
    });
  };

}).call(this);
