// Generated by CoffeeScript 1.9.1
(function() {
  'use strict';
  var shops_db;

  shops_db = require('../../models/shops_db');

  module.exports = function(req, res, next) {
    var shop;
    console.log('CREATION');
    console.log(req.body);
    shop = req.body;
    shops_db.shops.save(shop, function(err, res) {
      console.log(res);
    });
    next();
  };

}).call(this);
