// Generated by CoffeeScript 1.9.1
(function() {
  var bills_db, couch;

  couch = require('./couch');

  bills_db = couch.getDb('h_bills', function() {});

  module.exports.bills = bills_db;

}).call(this);
