// Generated by CoffeeScript 1.9.1
(function() {
  var bills_db, couch;

  couch = require('./couch');

  bills_db = couch.getDb('h_bills', function() {
    bills_db.save('_design/all', {
      all: {
        map: function(doc) {
          return emit(doc.date, null);
        }
      }
    });
  });

  module.exports = bills_db;

}).call(this);
