// Generated by CoffeeScript 1.9.1
(function() {
  var categories_db, couch;

  couch = require('./couch');

  categories_db = couch.getDb('h_categories', function() {
    categories_db.save('_design/all', {
      all: {
        map: function(doc) {
          if (doc.title) {
            return emit(doc._id, null);
          }
        }
      }
    });
    categories_db.save('_design/byTitle', {
      byTitle: {
        map: function(doc) {
          return emit(doc.title, null);
        }
      }
    });
  });

  module.exports = categories_db;

}).call(this);
