// Generated by CoffeeScript 1.9.1
(function() {
  var couch, cradle, express;

  express = require('express');

  cradle = require('cradle');

  console.log('hhhhhhhhhhhh');

  couch = function() {
    var con, db;
    con = new cradle.Connection('http://localhost', 5984, {
      cache: true,
      raw: false,
      forceSave: true,
      auth: {
        username: 'root',
        password: 'StrongPassWord'
      }
    });
    db = con.database('starwars');
    db.create(function(err) {
      console.log('err');
      return console.log(err);
    });
    db.save('vader', {
      name: 'darth',
      force: 'dark'
    }, function(err, res) {});
    return db.exists(function(err, exists) {
      if (err) {
        console.log('error', err);
      } else if (exists) {
        console.log('the force is with you.');
      } else {
        console.log('database does not exists.');
        db.create();
      }

      /* populate design documents */
    });
  };

  module.exports = couch;

}).call(this);
