// Generated by CoffeeScript 1.9.1
(function() {
  var couch, purchases_db;

  couch = require('./couch');

  purchases_db = couch.getDb('h_purchases', function() {});

  module.exports.purchases = purchases_db;

}).call(this);
