// Generated by CoffeeScript 1.9.1
(function() {
  var couch, shops_db;

  couch = require('./couch');

  shops_db = couch.getDb('h_shops', function() {
    shops_db.save('_design/all', {
      all: {
        map: function(doc) {
          if (doc.title) {
            return emit(doc._id, null);
          }
        }
      }
    });
  });

  module.exports = shops_db;

}).call(this);
